# Generated by Django 4.2.4 on 2023-08-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0002_manual_manual_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual',
            name='manual_file',
        ),
    ]
