# Generated by Django 4.2.4 on 2023-08-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0003_remove_manual_manual_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='manual_file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
